package com.arcusys.valamis.web.servlet.lrsProxy

import org.apache.http.HttpHeaders._

object ProxyConstants {
  val Method = "method"
  val Content = "content"
  val TincanHeader = "X-Experience-API-Version"
  val HttpHeaders = Seq(ACCEPT,
    ACCEPT_CHARSET,
    ACCEPT_ENCODING,
    ACCEPT_LANGUAGE,
    ACCEPT_RANGES,
    AGE,
    ALLOW,
    AUTHORIZATION,
    CACHE_CONTROL,
    CONNECTION,
    CONTENT_ENCODING,
    CONTENT_LANGUAGE,
    CONTENT_LENGTH,
    CONTENT_LOCATION,
    CONTENT_MD5,
    CONTENT_RANGE,
    CONTENT_TYPE,
    DATE,
    DAV,
    DEPTH,
    DESTINATION,
    ETAG,
    EXPECT,
    EXPIRES,
    FROM,
    HOST,
    IF,
    IF_MATCH,
    IF_MODIFIED_SINCE,
    IF_NONE_MATCH,
    IF_RANGE,
    IF_UNMODIFIED_SINCE,
    LAST_MODIFIED,
    LOCATION,
    LOCK_TOKEN,
    MAX_FORWARDS,
    OVERWRITE,
    PRAGMA,
    PROXY_AUTHENTICATE,
    PROXY_AUTHORIZATION,
    RANGE,
    REFERER,
    RETRY_AFTER,
    SERVER,
    STATUS_URI,
    TE,
    TIMEOUT,
    TRAILER,
    TRANSFER_ENCODING,
    UPGRADE,
    USER_AGENT,
    VARY,
    VIA,
    WARNING,
    WWW_AUTHENTICATE,
    TincanHeader)
}
